name: gift_grab_game
description: "A new Flutter package project."
version: 0.0.1
publish_to: "none"

environment:
  sdk: ^3.8.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.7
  flame: ^1.28.0
  flame_audio: ^2.11.4
  flame_bloc: ^1.12.11
  flutter_bloc: ^9.1.1
  # formz: ^0.8.0
  gap: ^3.0.1
  # go_router: ^16.0.0
  # toastification: ^3.0.3
  # dio: ^5.8.0+1
  # grpc: ^4.1.0
  gift_grab_ui:
    path: /Users/treyhope/Desktop/Development/gift_grab_ui

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

 
flutter:

 
  